// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfY_Wp4BmjKP0KsYZfjApHH81F3pMaCSk',
    appId: '1:208372480659:web:841c3414b32780c9cdeb66',
    messagingSenderId: '208372480659',
    projectId: 'test-project-56a86',
    authDomain: 'test-project-56a86.firebaseapp.com',
    storageBucket: 'test-project-56a86.firebasestorage.app',
    measurementId: 'G-0JH2WZFQ8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjo6GDzdL-oAaSD3Z1g4jPvLWO06pnu7k',
    appId: '1:208372480659:android:8da33c83ce65a354cdeb66',
    messagingSenderId: '208372480659',
    projectId: 'test-project-56a86',
    storageBucket: 'test-project-56a86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4M0THlE6l8dxHqKxR3Fs_r6DCkGdWsJE',
    appId: '1:208372480659:ios:09500eaae14dad10cdeb66',
    messagingSenderId: '208372480659',
    projectId: 'test-project-56a86',
    storageBucket: 'test-project-56a86.firebasestorage.app',
    iosBundleId: 'com.example.hw1',
  );

}